import type { AppData } from "@/lib/types"

const now = "2026-05-20T12:00:00.000Z"

export const demoData: AppData = {
  courses: [
    {
      id: "course-database",
      name: "数据库系统",
      teacher: "陈老师",
      color: "#0f766e",
      semester: "2025-2026 春季",
      description: "SQL、事务、索引与数据库设计复习资料集中地。",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course-math",
      name: "高等数学",
      teacher: "李老师",
      color: "#2563eb",
      semester: "2025-2026 春季",
      description: "期末复习、习题课讲义与历年题整理。",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course-english",
      name: "大学英语",
      teacher: "王老师",
      color: "#d97706",
      semester: "2025-2026 春季",
      description: "作文模板、听力材料和小组展示安排。",
      createdAt: now,
      updatedAt: now,
    },
  ],
  materials: [
    {
      id: "material-db-review",
      courseId: "course-database",
      fileName: "数据库系统期末复习提纲.pdf",
      type: "review",
      tags: ["复习", "期末", "重点"],
      uploadedAt: "2026-05-18T09:30:00.000Z",
      note: "老师群里发的最终版。",
    },
    {
      id: "material-math-exam",
      courseId: "course-math",
      fileName: "高数历年题整理.docx",
      type: "exam",
      tags: ["考试", "真题"],
      uploadedAt: "2026-05-17T14:20:00.000Z",
    },
    {
      id: "material-english-writing",
      courseId: "course-english",
      fileName: "四级作文模板合集.pdf",
      type: "reading",
      tags: ["作文", "模板"],
      uploadedAt: "2026-05-16T19:00:00.000Z",
    },
  ],
  todos: [
    {
      id: "todo-db-homework",
      courseId: "course-database",
      title: "提交数据库实验报告 4",
      deadline: "2026-05-28T23:59:00.000Z",
      submitMethod: "学习通提交",
      status: "pending",
      tags: ["实验", "作业"],
      sourceNoticeId: "notice-db-homework",
      createdAt: "2026-05-18T10:00:00.000Z",
      updatedAt: "2026-05-18T10:00:00.000Z",
    },
    {
      id: "todo-english-presentation",
      courseId: "course-english",
      title: "完成大学英语小组展示 PPT",
      deadline: "2026-05-24T20:00:00.000Z",
      submitMethod: "群文件提交",
      status: "pending",
      tags: ["小组", "展示"],
      sourceNoticeId: "notice-english-presentation",
      createdAt: "2026-05-16T10:00:00.000Z",
      updatedAt: "2026-05-16T10:00:00.000Z",
    },
  ],
  notices: [
    {
      id: "notice-db-homework",
      rawText: "数据库系统实验报告4请在5月28日23:59前提交到学习通，文件命名为学号+姓名。",
      courseId: "course-database",
      extractedTitle: "提交数据库实验报告 4",
      extractedDeadline: "2026-05-28T23:59:00.000Z",
      submitMethod: "学习通提交",
      tags: ["实验", "作业"],
      createdAt: "2026-05-18T10:00:00.000Z",
    },
    {
      id: "notice-english-presentation",
      rawText: "大学英语小组展示PPT周日前发到群文件，课堂会抽查展示顺序。",
      courseId: "course-english",
      extractedTitle: "完成大学英语小组展示 PPT",
      extractedDeadline: "2026-05-24T20:00:00.000Z",
      submitMethod: "群文件提交",
      tags: ["小组", "展示"],
      createdAt: "2026-05-16T10:00:00.000Z",
    },
  ],
}
